package:
  name: carnelian
  version: 'v0.6.0'

source:
  url: https://github.com/snz20/carnelian/archive/v0.6.1.tar.gz
  sha256: 462e617929e0f712a21dfad072328d07bf099f7c378b39fd5a7acf87a364da29

build:
  number: 1
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - python
    - boost
    - libtool
    - automake
    - autoconf
  host:
    - python
    - pip
    - zlib
  run:
    - zlib
    - python==2.7.3
    - numpy==1.12.1
    - pandas==0.19.2
    - scikit-learn==0.19.1
    - R==3.3.2
    - biopython==1.70

test:
  commands:
    -python carnelian.py -h

about:
  home: http://carnelian.csail.mit.edu/
  license: MIT
  summary: Alignment-free functional binning of whole metagenomic sequencing reads 
